sonar.projectKey=UPT-FAING-EPIS_proyecto-si783-2026-i-u1-generador-de-diagramas-de-base
sonar.organization=upt-faing-epis
sonar.projectName=DBCanvas - Generador de Diagramas de Base de Datos
sonar.projectVersion=1.0

sonar.sources=apps/web/app,apps/web/components,apps/web/lib,apps/web/actions,apps/web/store
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx,**/coverage/**

sonar.typescript.lcov.reportPaths=apps/web/coverage/lcov.info
sonar.coverage.exclusions=**

sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
